// src/lib/resume.svelte
<script lang="ts">
import Fa from "svelte-fa";
import { faGoogleDrive } from '@fortawesome/free-brands-svg-icons';
</script>
<!-- PAGES -->
<div class="flex flex-col sm:flex-row items-center gap-y-6">
  <div class="basis-auto sm:basis-2/3 p-6 sm:pt-0 text-center">
    <h1 class="font-bold text-7xl text-[#E5DCC5] pt-12 sm:pt-0">resume</h1>
  </div>
  <div class="card object-contain basis-1/6 w-84 sm:basis-1/4 p-4 sm:pt-30">
    <figure class="group transition-all duration-500 ease-in-out hover:scale-105 hover:rounded-xl hover:border-4 hover:border-[#c14153]">
      <a href="https://drive.google.com/file/d/1jd2WKaapmU2YjLHcehOiUCtWwxAwMZgM/view?usp=share_link" target="_blank" rel="noreferrer noopener">
        <img class="rounded-lg hover:scale-105" src="/darron_resume.png" alt="Resume"/>
      </a>
    </figure>
    <div class="card-body items-center">
      <h2 class="card-title">
        CV
        <div class="badge bg-[#c14153]">Darron Approved</div>
      </h2>
      <div class="card-actions justify-center">
        <div class="badge badge-outline">Professional</div>
        <div class="btn badge badge-outline bg-[#34A853]">
          <a href="https://drive.google.com/file/d/1jd2WKaapmU2YjLHcehOiUCtWwxAwMZgM/view?usp=share_link" target="_blank" rel="noreferrer noopener">
            <Fa icon={faGoogleDrive}/>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

// src/resume.jsx
//imports
import React from "react";
import { motion } from "framer-motion";

const Resume = () => (
  <div>
    <div>
      <motion.h1
        className="
  text-center
  font-oswald
  font-semibold
  mt-8
  text-[#4b3b42]
  leading-[1.25em]
    text-[5em]
    sm:text-[6em]
    md:text-[7em]
    lg:text-[8em]
    xl:text-[9em]
    2xl:text-[10em]
  "
        whileHover={{ scale: 1.1 }}
        whileTap={{ scale: 0.9 }}
      >
        Resume
      </motion.h1>
      <img
        src="/Resume.png"
        className="
    mt-8
    sm:mt-6
    md:mt-8
  block
  mx-auto
  border-5
  border-[#4b3b42]
    rounded-[8px]
  w-[35vw]
  max-w-md
  h-auto
  "
        alt="My resume"
      />{" "}
      <div
        className="
  flex flex-col items-center w-full mt-4
  "
      >
        <a
          href="https://drive.google.com/drive/u/0/folders/1c2qjx02dvd33weYW3Kl--AZ2PDeWdgob"
          target="_blank"
          rel="noopener noreferrer"
          className="
  font-garamond
  text-[#9c8481]
  m-20
  inline-block
  text-[1.75rem]
  text-center
  hover:text-blue-500
  "
        >
          <i className="fa-brands fa-google-drive"></i> Download
        </a>
      </div>
    </div>
  </div>
);

export default Resume;
